// export const CARRER_IMG= require('../../Assets/images/career_img.png');
export const CARRER_BENFIT_IMG=require("../../Assets/images/about-1.jpg");
export const JOIN_OUR_TEAM_IMG = require("../../Assets/images/join_our_team.png");
export const CAREERS_AT_SAKSHATH = require("../../Assets/images/careers_at_sakshath.png");
export const REACT_LOGO = require("../../Assets/images/physics.png");
export const EXPRESSIVE = require("../../Assets/images/expressive.png");
export const MOTIVATED = require("../../Assets/images/motivated.png");
export const ARTICULATE = require("../../Assets/images/articulate.png");
export const NEW_CHALLENGES = require("../../Assets/images/new_challenge.png");
